language: ruby
sudo: false
cache: bundler

rbenv:
  - 2.3.7

services:
  - postgresql

addons:
  chrome: stable

install:
  - bundle install --jobs=3 --retry=3 --without production

before_script:
  - cp env.example .env
  - psql -c 'create database kudo_o_matic_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - bundle exec rails db:migrate

script:
  - bundle exec rspec

notifications:
  email: false

