defaults: &defaults
  token_expiration_time: <%= 1.month %>
  max_edit_and_delete_time: <%= 15 * 60 %> # 15 minutes
  gravatar_style: 'retro'
  gravatar_size: '200'
  slack_acccess_token_endpoint: 'https://slack.com/api/oauth.v2.access'
  slack_post_message_endpoint: 'https://slack.com/api/chat.postMessage'
  slack_connect_success_url: 'http://localhost:9090/#/manage-team/integrations?auth=ok'

development:
  <<: *defaults
  max_edit_and_delete_time: <%= 24 * 60 * 60 %> # 24 hours

staging:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults