defaults: &defaults
  token_expiration_time: <%= 1.month %>
  max_edit_and_delete_time: <%= 15 * 60 %> # 15 minutes
  gravatar_style: 'retro'
  gravatar_size: '200'

development:
  <<: *defaults
  max_edit_and_delete_time: <%= 24 * 60 * 60 %> # 24 hours

staging:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults