defaults: &defaults
  token_expiration_time: <%= 1.month %>
  gravatar_style: 'retro'
  gravatar_size: '200'

development:
  <<: *defaults

staging:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults