name: Ruby

on: [push, pull_request]
  
jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      db:
        image: postgres:11

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1.32.1      
      with:
        ruby-version: 2.5.4
    - name: Build and test with Rake
      env:
        RAILS_ENV: test
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rails db:migrate
        bundle exec rspec
