name: Rails run RSpec tests

on: [push, pull_request]
  
jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      db:
        image: postgres:11

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1.32.1      
      with:
        ruby-version: 2.5.4
    - name: Install dependencies and setup db
      env:
        RAILS_ENV: test
      run: |
        gem install bundler
        bundle install --jobs=3 --retry=3 --without production
        bundle exec rails db:create
        bundle exec rails db:migrate
    - name: Run tests
      env:
        RAILS_ENV: test
      run: |
        bundle exec rspec
      
        
